# Generated by Django 4.2.3 on 2023-07-17 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0004_remove_resident_id_alter_resident_resident_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("1", "Institutional ID"),
                            ("2", "Aadhar Number"),
                            ("3", "Voter ID"),
                            ("4", "Driving License"),
                            ("5", "Passport"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "In Process"), ("1", "Verified")], max_length=1
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="user.resident"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_applied", models.DateTimeField(auto_now_add=True)),
                ("room_applied", models.CharField(default="xxx", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "In Process"), ("1", "Confirmed")], max_length=1
                    ),
                ),
                (
                    "applicant",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.resident",
                    ),
                ),
            ],
        ),
    ]
