# Generated by Django 4.2.3 on 2023-07-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_resident_id_alter_resident_resident_id"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verification",
            name="id_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="verification",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="user.resident",
            ),
        ),
    ]
