# Generated by Django 4.2.3 on 2023-07-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_verification_id_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verification",
            name="id_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="verification",
            unique_together={("id_type", "id_number")},
        ),
    ]
