# Generated by Django 4.2.3 on 2023-07-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_verification_id_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("0", "In Process"), ("1", "Confirmed")],
                default="0",
                max_length=1,
            ),
        ),
    ]
