# Generated by Django 4.2.3 on 2023-07-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_resident_check_in_date"),
        ("core", "0004_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="applicant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.resident",
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="status",
            field=models.CharField(
                choices=[("0", "In Process"), ("1", "Verified")],
                default="0",
                max_length=1,
            ),
        ),
    ]
