# Generated by Django 4.2.3 on 2023-07-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_number",
                    models.CharField(
                        max_length=3, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        choices=[
                            ("1", "First"),
                            ("2", "Second"),
                            ("3", "Third"),
                            ("4", "Fourth"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "Single"), ("2", "Double"), ("3", "Triple")],
                        max_length=1,
                    ),
                ),
                ("ac", models.BooleanField(blank=True, null=True)),
                ("occupied", models.BooleanField(default=False)),
            ],
        ),
    ]
