# Generated by Django 4.2.3 on 2023-07-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_remove_payment_transaction_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="first_payment",
        ),
    ]
