# Generated by Django 4.2.3 on 2023-07-10 10:47

from django.db import migrations
import user.manager


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.manager.UserManager()),
            ],
        ),
    ]
