# Generated by Django 4.2.3 on 2023-07-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_resident_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="resident_id",
            field=models.SlugField(default="xxxx"),
        ),
    ]
