# Generated by Django 4.2.3 on 2023-07-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_resident_id_alter_resident_resident_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="check_in_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
