# Generated by Django 4.2.3 on 2023-07-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_resident_check_in_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
